In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 4])
print(a)

[1 2 4]


In [3]:
b = np.array([[3.0, 2.0, 1.0], [4.0, 5.2, 6.9], [9.23, 8.1, 7.43]])
print(b)

[[3.   2.   1.  ]
 [4.   5.2  6.9 ]
 [9.23 8.1  7.43]]


In [4]:
# ndim returns the number of dimensions of an array
print(a.ndim, b.ndim)
# size returns the number of elements in an array
print(a.size, b.size)
# shape returns a tuple of the number of elements stored in each dimension of an array. 
# for example, a 2d array may have row length of 2, and column length of 3.
print(a.shape, b.shape)

1 2
3 9
(3,) (3, 3)


In [5]:
# type returns the type of the array
print(a.dtype, b.dtype)

int64 float64


In [6]:
# specifying the type of an array
c = np.array([10, 12, 13], dtype='int16')
print(c, c.dtype)

[10 12 13] int16


In [7]:
# get size (byte)
print(a.itemsize, b.itemsize, c.itemsize)

8 8 2


In [8]:
# get total size
print(a.nbytes, b.nbytes, c.nbytes)

24 72 6


### **Accessing/Changing Specific elements, rows, columns, etc.**

In [9]:
a = np.array([[1,2,3,4,5,6,7],
              [2,5,2,3,5,7,3]])
print(a)

[[1 2 3 4 5 6 7]
 [2 5 2 3 5 7 3]]


In [10]:
# get specific elements using a[row, column]
a[1,2]

2

In [11]:
# get specific row
a[0, :] # first row

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# get specific column
a[:, 0] # first column

array([1, 2])

In [13]:
# get elements by iterating with steps a[row, start:end+1:steps]
print(a[0, 0:7:2])
print(a[0, 0:-2:2])

[1 3 5 7]
[1 3 5]


In [14]:
# replace index with element
a[0,1] = 10
print(a)
a[0, 2:5] = 11 # replace a range of index with an element
print(a)

[[ 1 10  3  4  5  6  7]
 [ 2  5  2  3  5  7  3]]
[[ 1 10 11 11 11  6  7]
 [ 2  5  2  3  5  7  3]]


### **Initialize different types of arrays**

In [15]:
# all elements are zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# all elements are ones
b = np.ones((4,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# all elements are the same number (full)
c = np.full((2,2,2), 50)
print(c, '\n-=-=-=-=-=-=-=-=-=-=-=-')
## make array full of a number with the same shape as another array
print(np.full_like(c, 12))

[[[50 50]
  [50 50]]

 [[50 50]
  [50 50]]] 
-=-=-=-=-=-=-=-=-=-=-=-
[[[12 12]
  [12 12]]

 [[12 12]
  [12 12]]]


In [18]:
# create an array of random decimal numbers.
print(np.random.rand(2, 5), "\n-=-=-=-=-=-=-=-=-=-=-=-=-")
# create an array of random decimal numbers with the same shape as another arrays
print(np.random.random(b.shape))

[[0.14792517 0.1104268  0.48459503 0.36352395 0.90202076]
 [0.49238809 0.10886163 0.20510947 0.37686414 0.40857656]] 
-=-=-=-=-=-=-=-=-=-=-=-=-
[[0.91111086 0.21214041 0.21420014 0.84782763]
 [0.01844939 0.08796675 0.10109589 0.46859338]
 [0.59452481 0.53994729 0.55446939 0.48801728]
 [0.16074032 0.03343995 0.91118499 0.09790671]]


In [19]:
# create an array of random integers
print(np.random.default_rng().integers(10, 15, size=(2,4)))
print("\n============================")
# using randit (deprecated)
print(np.random.randint(5, 15, size=(2,4)))

[[14 11 11 14]
 [13 11 10 13]]

[[ 9  7 12  5]
 [12  9  5 11]]


[](http://)

In [20]:
# create an identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# repeat an array
print(np.repeat([[1,2,3]], 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
# array challenge
d = np.zeros((5,5))
d[0] = np.ones((1,5))
d[4] = np.repeat(d[0], 1, axis=0)
d[:,0] = np.repeat(d[0], 1, axis=0)
d[:,4] = np.repeat(d[0], 1, axis=0)
d[2,2] = 9

# array challenge #2
output = np.ones((5,5))
output[1:-1,1:-1] = np.zeros((3,3))
output[2,2] = 9
print(d)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying arrays !! (IMPORTANT)

In [23]:
# when copying array use the copy() method

a = np.array([1,2,3])
b = a
b[0] = 999

print(a) # as you can see b points to the same object as a, therefore when we set b[0] to 999 it also changes a

# using copy() method

a = np.array([1,2,3])
b = a.copy()
b[0] = 999

print(a) # changing elements in b will no longer change a

[999   2   3]
[1 2 3]
