In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 4])
print(a)

[1 2 4]


In [3]:
b = np.array([[3.0, 2.0, 1.0], [4.0, 5.2, 6.9], [9.23, 8.1, 7.43]])
print(b)

[[3.   2.   1.  ]
 [4.   5.2  6.9 ]
 [9.23 8.1  7.43]]


In [4]:
# ndim returns the number of dimensions of an array
print(a.ndim, b.ndim)
# size returns the number of elements in an array
print(a.size, b.size)
# shape returns a tuple of the number of elements stored in each dimension of an array. 
# for example, a 2d array may have row length of 2, and column length of 3.
print(a.shape, b.shape)

1 2
3 9
(3,) (3, 3)


In [5]:
# type returns the type of the array
print(a.dtype, b.dtype)

int64 float64


In [6]:
# specifying the type of an array
c = np.array([10, 12, 13], dtype='int16')
print(c, c.dtype)

[10 12 13] int16


In [7]:
# get size (byte)
print(a.itemsize, b.itemsize, c.itemsize)

8 8 2


In [8]:
# get total size
print(a.nbytes, b.nbytes, c.nbytes)

24 72 6


### **Accessing/Changing Specific elements, rows, columns, etc.**

In [9]:
a = np.array([[1,2,3,4,5,6,7],
              [2,5,2,3,5,7,3]])
print(a)

[[1 2 3 4 5 6 7]
 [2 5 2 3 5 7 3]]


In [10]:
# get specific elements using a[row, column]
a[1,2]

2

In [11]:
# get specific row
a[0, :] # first row

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# get specific column
a[:, 0] # first column

array([1, 2])

In [13]:
# get elements by iterating with steps a[row, start:end+1:steps]
print(a[0, 0:7:2])
print(a[0, 0:-2:2])

[1 3 5 7]
[1 3 5]


In [14]:
# replace index with element
a[0,1] = 10
print(a)
a[0, 2:5] = 11 # replace a range of index with an element
print(a)

[[ 1 10  3  4  5  6  7]
 [ 2  5  2  3  5  7  3]]
[[ 1 10 11 11 11  6  7]
 [ 2  5  2  3  5  7  3]]


### **Initialize different types of arrays**

In [15]:
# all elements are zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# all elements are ones
b = np.ones((4,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# all elements are the same number (full)
c = np.full((2,2,2), 50)
print(c, '\n-=-=-=-=-=-=-=-=-=-=-=-')
## make array full of a number with the same shape as another array
print(np.full_like(c, 12))

[[[50 50]
  [50 50]]

 [[50 50]
  [50 50]]] 
-=-=-=-=-=-=-=-=-=-=-=-
[[[12 12]
  [12 12]]

 [[12 12]
  [12 12]]]


In [18]:
# create an array of random decimal numbers.
print(np.random.rand(2, 5), "\n-=-=-=-=-=-=-=-=-=-=-=-=-")
# create an array of random decimal numbers with the same shape as another arrays
print(np.random.random(b.shape))

[[0.86328425 0.40835851 0.15584125 0.81606507 0.09087124]
 [0.15391774 0.46248124 0.85837404 0.93300995 0.04067577]] 
-=-=-=-=-=-=-=-=-=-=-=-=-
[[0.83456427 0.15651951 0.44539368 0.80085094]
 [0.83193322 0.90755154 0.42566939 0.4918701 ]
 [0.48190449 0.89934784 0.42211709 0.2129445 ]
 [0.79079169 0.66593122 0.60177664 0.58433512]]


In [19]:
# create an array of random integers
print(np.random.default_rng().integers(10, 15, size=(2,4)))
print("\n============================")
# using randit (deprecated)
print(np.random.randint(5, 15, size=(2,4)))

[[14 14 10 10]
 [14 11 14 12]]

[[14  7 13 12]
 [ 9  5  6  8]]


[](http://)

In [20]:
# create an identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# repeat an array
print(np.repeat([[1,2,3]], 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
# array challenge
d = np.zeros((5,5))
d[0] = np.ones((1,5))
d[4] = np.repeat(d[0], 1, axis=0)
d[:,0] = np.repeat(d[0], 1, axis=0)
d[:,4] = np.repeat(d[0], 1, axis=0)
d[2,2] = 9

# array challenge #2
output = np.ones((5,5))
output[1:-1,1:-1] = np.zeros((3,3))
output[2,2] = 9
print(d)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### **Copying arrays !! (IMPORTANT)**

In [23]:
# when copying array use the copy() method

a = np.array([1,2,3])
b = a
b[0] = 999

print(a) # as you can see b points to the same object as a, therefore when we set b[0] to 999 it also changes a

# using copy() method

a = np.array([1,2,3])
b = a.copy()
b[0] = 999

print(a) # changing elements in b will no longer change a

[999   2   3]
[1 2 3]


### **Mathematics**

In [24]:
# you can perform arithmetic on the arrays!
a = np.array([1,2,3,4,5])

In [25]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [26]:
b = np.array([1.4, 1.6, 1.8, 2.0, 2.2])
c = a + b

In [27]:
# mathematical functions! more: https://numpy.org/doc/stable/reference/routines.math.html
print("sin a", np.sin(a))
print("cos a", np.cos(a))
print("ceil c", np.ceil(c))
print("floor c", np.floor(c))

sin a [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos a [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
ceil c [3. 4. 5. 6. 8.]
floor c [2. 3. 4. 6. 7.]


#### Linear Algebra

In [28]:
# matrix multiplication 
a = np.full((3,2), 3)
b = np.full((2,3), 4)
print("a\n", a)
print("b\n", b)

print("a*b\n", np.matmul(a,b))
print("b*a\n", np.matmul(b,a))

a
 [[3 3]
 [3 3]
 [3 3]]
b
 [[4 4 4]
 [4 4 4]]
a*b
 [[24 24 24]
 [24 24 24]
 [24 24 24]]
b*a
 [[36 36]
 [36 36]]


In [29]:
# identity matrix and determinant
c = np.identity(5)
np.linalg.det(c)

1.0

#### Statistics

In [30]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# min and max of array
print(np.min(stats, axis=0)) # get min of the horizonal axis
print(np.min(stats, axis=1)) # get min of vertical axis
print(np.max(stats)) # get maximum value 

[1 2 3]
[1 4]
6


In [32]:
# sum
print(np.sum(stats, axis=0)) # get sum of the horizontal axis - adds each element that are in the vertical axis
print(np.sum(stats, axis=1)) # get sum of the vertical axis - adds each element that are in the horizontal axis
print(np.sum(stats)) # get sum of array

[5 7 9]
[ 6 15]
21


### **Matrix Reorganizing**

In [33]:
# reshaping an array
before = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(before)

# reshaped arrays MUST have the same number of values as the original array
print("\n", before.reshape(3,4))
print("\n", before.reshape(6,2))
print("\n", before.reshape(3,2,2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [34]:
# stacking arrays - arrays need to have the same shape

a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

print(np.stack((a1,a2), axis=0))
print(np.stack((a1,a2), axis=1))

# vstack
print(np.vstack((a1,a2)))
# hstack
print(np.hstack((a1,a2)))

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### **Miscellaneous**

#### Loading data from file

In [35]:
filedata = np.genfromtxt('/kaggle/input/test-input-numpy/testdata.txt', delimiter=',', dtype='int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [36]:
# Boolean masking
# broadcast array with conditional operator
print(filedata < 5, "\n") # will return a boolean array
print((filedata > 5) & (filedata < 15))

[[ True  True  True  True False False False False]
 [False False False False False False False False]
 [False False False False False False False False]] 

[[False False False False False  True  True  True]
 [ True  True  True  True  True  True False False]
 [False False False False False False False False]]


In [37]:
# using any(or) to test for true on a specific axis
print(np.any(filedata < 5, axis=0)) # returns True if a column contains an element < 5
print(np.any(filedata < 5, axis=1)) # returns True if a row contains an element < 5

# using all(and) to test for true on a specific axis
print(np.all(filedata < 5, axis=0)) # returns True if all elements in a column is < 5

[ True  True  True  True False False False False]
[ True False False]
[False False False False False False False False]


In [38]:
# Advanced indexing
# indexing using conditional operations
print(filedata[filedata < 5]) # return array where element < 5

[1 2 3 4]


In [39]:
# indexing using a list
a = np.array([10,9,8,7,6,5,4,3,2,1])
a[[0,4,9]]

array([10,  6,  1])